# Generated by Django 4.2.16 on 2026-01-18 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('talent', 'Talent'), ('agency', 'Agency'), ('agency_talent', 'Agency Talent')], default='talent', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='agency',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'agency'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_talents', to=settings.AUTH_USER_MODEL),
        ),
    ]
