# Generated by Django 4.2.16 on 2026-01-26 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_postreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_videos', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='accounts.video')),
            ],
            options={
                'db_table': 'favorite_videos',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'video')},
            },
        ),
    ]
