# Generated by Django 4.2.16 on 2026-01-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_groupconversation_groupmessage_groupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
