# Generated by Django 4.2.16 on 2026-01-29 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_bio_genre_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteTalent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_talents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite_talents',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'talent')},
            },
        ),
    ]
