# Generated by Django 4.2.16 on 2026-01-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_favorite_talent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy_setting',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('hidden', 'Hidden')], default='public', max_length=10),
        ),
    ]
