# Generated by Django 4.2.16 on 2026-01-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_video_privacy_and_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='attachment_type',
            field=models.CharField(choices=[('none', 'None'), ('photo', 'Photo'), ('video', 'Video')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='attachment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_type',
            field=models.CharField(choices=[('none', 'None'), ('photo', 'Photo'), ('video', 'Video')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='content',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
