# Generated by Django 4.2.16 on 2026-01-30 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_photopost_photo'),
        ('accounts', '0016_messagereport'),
    ]

    operations = [
    ]
