# Generated by Django 4.2.16 on 2026-02-02 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_merge_0011_photopost_photo_0016_messagereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'folders',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FolderAccessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='accounts.folder')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_access_given', to=settings.AUTH_USER_MODEL)),
                ('granted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_access_granted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'folder_access_permissions',
                'ordering': ['-created_at'],
                'unique_together': {('folder', 'granted_to')},
            },
        ),
        migrations.CreateModel(
            name='FolderAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='accounts.folder')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'folder_access_requests',
                'ordering': ['-created_at'],
                'unique_together': {('folder', 'requester')},
            },
        ),
        migrations.CreateModel(
            name='Subfolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('privacy', models.CharField(choices=[('inherit', 'Inherit from parent'), ('public', 'Public'), ('private', 'Private')], default='inherit', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='accounts.folder')),
            ],
            options={
                'db_table': 'subfolders',
                'ordering': ['-created_at'],
                'unique_together': {('folder', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SubfolderAccessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfolder_access_given', to=settings.AUTH_USER_MODEL)),
                ('granted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfolder_access_granted', to=settings.AUTH_USER_MODEL)),
                ('subfolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='accounts.subfolder')),
            ],
            options={
                'db_table': 'subfolder_access_permissions',
                'ordering': ['-created_at'],
                'unique_together': {('subfolder', 'granted_to')},
            },
        ),
        migrations.CreateModel(
            name='SubfolderAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfolder_access_requests', to=settings.AUTH_USER_MODEL)),
                ('subfolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='accounts.subfolder')),
            ],
            options={
                'db_table': 'subfolder_access_requests',
                'ordering': ['-created_at'],
                'unique_together': {('subfolder', 'requester')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='videoaccessrequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='videoaccessrequest',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='videoaccessrequest',
            name='video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='privacy',
        ),
        migrations.DeleteModel(
            name='VideoAccessPermission',
        ),
        migrations.DeleteModel(
            name='VideoAccessRequest',
        ),
        migrations.AddField(
            model_name='photopost',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_posts', to='accounts.folder'),
        ),
        migrations.AddField(
            model_name='photopost',
            name='subfolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_posts', to='accounts.subfolder'),
        ),
        migrations.AddField(
            model_name='video',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='accounts.folder'),
        ),
        migrations.AddField(
            model_name='video',
            name='subfolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='accounts.subfolder'),
        ),
    ]
