# Generated by Django 4.2.16 on 2026-02-02 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_simplify_folder_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_folder_invite_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='privacy_setting',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.CreateModel(
            name='PrivateFolderAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_folder_access_requests_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_folder_access_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'private_folder_access_requests',
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'requester')},
            },
        ),
        migrations.CreateModel(
            name='PrivateFolderAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_folder_access_received', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_folder_access_granted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'private_folder_access',
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'granted_to')},
            },
        ),
    ]
