# Generated by Django 4.2.16 on 2026-02-03 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreport',
            name='photo_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.photopost'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('profile_access_request', 'Profile Access Request'), ('folder_access_request', 'Folder Access Request'), ('group_invite', 'Group Invite'), ('group_join_request', 'Group Join Request'), ('agency_talent_linked', 'Agency Talent Linked'), ('referral_added', 'Referral Added'), ('post_suspended', 'Post Suspended'), ('admin_new_talent', 'New Talent Signup'), ('admin_new_agency', 'New Agency Signup'), ('admin_post_report', 'New Post Report'), ('admin_message_report', 'New Message Report')], max_length=50),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('suspended', 'Suspended'), ('dismissed', 'Dismissed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.video'),
        ),
    ]
