# Generated by Django 4.2.16 on 2026-02-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_add_photo_post_to_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency_invite_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='messagereport',
            name='reason',
            field=models.CharField(choices=[('inappropriate', 'Inappropriate Message'), ('bullying', 'Bullying and Harassment'), ('fraudulent', 'Fraudulent Activity'), ('impersonation', 'Impersonation')], max_length=50),
        ),
    ]
