# Generated by Django 4.2.16 on 2026-02-04 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_update_email_constraints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photopost',
            name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.CreateModel(
            name='PostFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='accounts.postfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_folders',
                'ordering': ['name'],
                'unique_together': {('user', 'name', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='photopost',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_posts', to='accounts.postfolder'),
        ),
        migrations.AddField(
            model_name='video',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='accounts.postfolder'),
        ),
    ]
