# Generated by Django 4.2.16 on 2026-02-04 01:57

from django.db import migrations


def create_default_folders(apps, schema_editor):
    """Create default folder structure for all existing users"""
    User = apps.get_model('accounts', 'User')
    PostFolder = apps.get_model('accounts', 'PostFolder')
    
    for user in User.objects.all():
        # Create root "Posts" folder
        posts_folder = PostFolder.objects.create(
            user=user,
            name="Posts",
            is_default=True
        )
        
        # Create "Videos" subfolder
        PostFolder.objects.create(
            user=user,
            name="Videos",
            parent=posts_folder,
            is_default=True
        )
        
        # Create "Images" subfolder
        PostFolder.objects.create(
            user=user,
            name="Images",
            parent=posts_folder,
            is_default=True
        )


def reverse_create_default_folders(apps, schema_editor):
    """Remove all default folders"""
    PostFolder = apps.get_model('accounts', 'PostFolder')
    PostFolder.objects.filter(is_default=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_photopost_title_remove_video_title_postfolder_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_folders, reverse_create_default_folders),
    ]
