# Generated by Django 4.2.16 on 2026-02-05 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_add_reply_to_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('profile_access_request', 'Profile Access Request'), ('folder_access_request', 'Folder Access Request'), ('group_invite', 'Group Invite'), ('group_join_request', 'Group Join Request'), ('agency_talent_linked', 'Agency Talent Linked'), ('referral_added', 'Referral Added'), ('post_suspended', 'Post Suspended'), ('new_message', 'New Message'), ('new_group_message', 'New Group Message'), ('admin_new_talent', 'New Talent Signup'), ('admin_new_agency', 'New Agency Signup'), ('admin_post_report', 'New Post Report'), ('admin_message_report', 'New Message Report')], max_length=50),
        ),
        migrations.CreateModel(
            name='ProfileAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_access_requests_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_access_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_access_requests',
                'ordering': ['-created_at'],
                'unique_together': {('profile_owner', 'requester')},
            },
        ),
        migrations.CreateModel(
            name='ProfileAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_access_received', to=settings.AUTH_USER_MODEL)),
                ('profile_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_access_granted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_access',
                'ordering': ['-created_at'],
                'unique_together': {('profile_owner', 'granted_to')},
            },
        ),
    ]
