# Generated by Django 4.2.16 on 2026-02-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collaboration_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
