# Generated by Django 4.2.16 on 2026-02-05 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_postfolder_privacy_subfolder_privacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linked_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
