# Generated by Django 4.2.16 on 2026-02-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_add_admin_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency_tier',
            field=models.CharField(blank=True, choices=[('tier1', 'Tier 1'), ('tier2', 'Tier 2')], max_length=10, null=True),
        ),
    ]
