# Generated by Django 4.2.16 on 2026-02-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_user_stripe_customer_id_user_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='privacy_setting',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('hidden', 'Hidden')], default='public', max_length=10),
        ),
    ]
