# Generated by Django 4.2.16 on 2026-02-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_add_hidden_privacy_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopost',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('hidden', 'Hidden')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('hidden', 'Hidden')], default='public', max_length=10),
        ),
    ]
