# Generated by Django 4.2.16 on 2026-02-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_add_hidden_privacy_to_videos_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('profile_access_request', 'Profile Access Request'), ('profile_access_granted', 'Profile Access Granted'), ('profile_access_denied', 'Profile Access Denied'), ('folder_access_request', 'Folder Access Request'), ('private_folder_access_granted', 'Private Folder Access Granted'), ('private_folder_access_denied', 'Private Folder Access Denied'), ('group_invite', 'Group Invite'), ('group_join_request', 'Group Join Request'), ('agency_talent_linked', 'Agency Talent Linked'), ('referral_added', 'Referral Added'), ('post_suspended', 'Post Suspended'), ('new_message', 'New Message'), ('new_group_message', 'New Group Message'), ('admin_new_talent', 'New Talent Signup'), ('admin_new_agency', 'New Agency Signup'), ('admin_post_report', 'New Post Report'), ('admin_message_report', 'New Message Report')], max_length=50),
        ),
    ]
