# Generated by Django 4.2.16 on 2026-02-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upgraded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
